version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devevents_dev
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - devevents

  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devevents_test
    ports:
      - "5437:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    networks:
      - devevents

volumes:
  postgres_data:
  postgres_test_data:
networks:
  devevents: