"""create categories and events tables

Revision ID: 9d02adeef34e
Revises: a97c2504400c
Create Date: 2023-11-23 22:21:50.222899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d02adeef34e'
down_revision: Union[str, None] = 'a97c2504400c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.execute(
        "INSERT INTO categories (name) VALUES ('Drinks'), ('Culture'), ('Film'), ('Food'), ('Music'), ('Travel')")

    op.create_table('events',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(),
                              nullable=False, index=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('cover_image', sa.String(), nullable=True),
                    sa.Column('venue', sa.String(), nullable=False),
                    sa.Column('attendee_total', sa.Integer(),
                              nullable=False, default=0),
                    sa.Column('venue_lat', sa.Float(), nullable=False),
                    sa.Column('venue_lng', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sa.Integer(),
                              nullable=False, index=True),
                    sa.Column('category_id', sa.Integer(),
                              nullable=False, index=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('categories')
    # ### end Alembic commands ###
