name: Tests

on:
  push:
    branches:
      - fastapi

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          ACCESS_TOKEN_EXPIRE_SECONDS: '3600'
          SECRET_KEY: '12345678901234567890'
          ALGORITHM: 'KDKDKDK'
        run: |
          pytest
